### ISSUE TITLE
[Question] Is it a good idea to use PlotlyBase.jl in StipplePlotly ?

### ISSUE THREAD

**Issue by touchft** [GenieFramework/StipplePlotly.jl#10]
Just a quick guess: How about to use `PlotlyBase.jl` in `StipplePlotly` ? If so, `stipple` will keep plot style the same as in PlotlyJS/Plotly and make things simple!

**Comment by touchft** [comment]
I figure it out to include `PlotlyBase` in StipplePlotly and works perfectly! Can I make a PR ?

**Comment by essenciary** [comment]
@touchft Do you have an example please?

**Comment by touchft** [comment]
### Charts.jl ###
add and export PlotlyBase type: 
```julia
using PlotlyBase: AbstractTrace, AbstractLayout
export AbstractTrace, AbstractLayout
```

add `AbstractLayout` to `plot`'s input `layout`:
```julia
function plots(fieldname::Symbol;
              layout::Union{Symbol, PlotLayout, AbstractLayout} = PlotLayout(),
              wrap::Function = DEFAULT_WRAPPER,
              ...
```
### example ###
```julia
using Genie, Genie.Renderer.Html, Stipple, StipplePlotly
using PlotlyBase:Plot

Base.@kwdef mutable struct PlotModel <: ReactiveModel
    data::R{Vector{<:AbstractTrace}} = Plot(rand(10,2)).data
    layout::R{AbstractLayout} = Plot(rand(10,2)).layout
end

pltmodel = Stipple.init(PlotModel())

function ui(RModel::ReactiveModel)
  page(
    vm(RModel), class="container", [
      plots(:data, layout = :layout)
    ]
  ) |> html
end

route("/") do
    ui(pltmodel)
end

up(8800, open_browser=false)

for i in 1:100
    pltmodel.data[] = Plot(rand(100,2)).data
    sleep(0.1)
end
```

**Comment by essenciary** [comment]
@touchft Thanks, this could be brilliant as we could rely on PlotlyBase instead of implementing and maintaining our own API. I need to taka a closer look though to understand why/how it works :)

**Comment by touchft** [comment]
@essenciary [Plotly](http://juliaplots.org/PlotlyJS.jl/stable/basics/) **User Guide** part may be a help except the the *Julia types* section may is out of date comparing with the updated Plotly package.

**Comment by hhaensel** [comment]
I had a very similar idea and was not aware of this post.

In my opinion it is a great idea, because PlotlyBase's implementation gives quite some more flexibility by using Dicts instead of structs. Furthermore, they have the very nice syntax of creating subdicts by the `'_'` character.

I think the solution works, because in PlotlyBase all kwargs are Dicts and they are rendered correctly.

@touchft 's example is great because it is non-breaking and very lean. To be consistent, also the config should be modified along the same lines.

 @essenciary what do you think?

**Comment by essenciary** [comment]
Indeed, I'm of the same opinion. I'm still not sure about the Dict vs Structs approach (there are pros and cons for both and I'd like to have a uniform approach between StippleCharts and StipplePlotly) but I'm all for having Dict/PlotlyBase compatibility. That seems to already work and it would be great, as a first iteration, to officially support it alongside the current custom structs architecture. Makes sense?

**Comment by hhaensel** [comment]
Not sure whether we really see the advantage of structs versus dicts. For broadcasting we use a dictionary anyhow ...
If dict preformance is really an issue, we might consider using @andyferris 's Dictionaries.jl.

**Comment by essenciary** [comment]
I'm open to scraping the structs, they require a lot of manual work to map the JS API, leading to incompleteness, long term continuous maintainance work, etc.

**Comment by essenciary** [comment]
I like structs for neatness (self-documenting, discovery of fields through auto-complete, compiler validation/no-typos-in-keys, etc). Performance could also be a plus.

**Comment by andyferris** [comment]
`Dict` performance isn’t _bad_ in Julia. As I understand it, they are as fast as Python, or perhaps JavaScript (for `Map` or unspecialized objects). Which is fast - but that’s not the same speed as a struct in C, so it depends on your use case.

In case this is relevant, I’ve been thinking of making a kind of wrapper for `AbstractDictionary{Symbol}` that exposes the property interface (which amongst other things, gives you autocomplete at the REPL).

**Comment by cwiese** [comment]
This is an extremely useful approach.  I have been trying to add "shapes" to Layout.   With this approach there is no need to dually maintain changes to the API.    If I create a PR to Charts.jl that @touchft has specified .. will it be merged?

**Comment by hhaensel** [comment]
You're welcome to submit a PR. We'll definitely review it!

**Comment by hhaensel** [comment]
I just digged a bit in this topic.

Currently, `plot(:data, layout = :layout, config = :config)` fails if not all of the kwargs are defined by the model.
This can be fixed by defining
```julia
Base.print(io::IO, a::Union{PlotLayout, StipplePlotly.PlotConfig}) = print(io, Stipple.json(a))
```

Furthermore, if we want to accept other types, we might do so by releasing the restriction of the layout and config type or we could enhance the type upon loading of PlotlyBase via `@require`.

A solution that does already work without any changes is the following
```julia
using StippleUI, PlotlyBase
import Stipple.json

Base.print(io::IO, a::Union{PlotLayout, StipplePlotly.PlotConfig, PlotlyBase.PlotConfig}) = print(io, Stipple.json(a))
StructTypes.StructType(::Type{<:PlotlyBase.HasFields}) = JSON3.RawType()
StructTypes.StructType(::Type{PlotlyBase.PlotConfig}) = JSON3.RawType()

JSON3.rawbytes(x::Union{PlotlyBase.Plot,PlotlyBase.HasFields,PlotlyBase.PlotConfig}) = codeunits(PlotlyBase.JSON.json(x))
```
then you can do
```julia
xelem(:plotly, data = :data, layout = @data(PlotlyBase.Layout()), config = @data(PlotlyBase.PlotConfig()))

model.data[] = Plot(rand(100,2)).data
```
is already possible, the only thing you need to do is to modify the type of the model fields, e.g.
```julia
@reactive! mutable struct Model <: ReactiveModel
    data::R{Vector} = [pd("Random 1"), pd("Random 2")], READONLY
    layout::R{Union{PlotlyBase.Layout, PlotLayout}} = PlotLayout(
        plot_bgcolor = "#333",
        title = PlotLayoutTitle(text = "Random numbers", font = Font(24)),
    ), READONLY
    config::R{Union{StipplePlotly.PlotConfig, PlotlyBase.PlotConfig}} = PlotConfig(), READONLY
end
```

@essenciary 
What do you think?
- Shall we include above definitions (the ones without PlotlyBase)
- Shall we enhance the accepted types of plot via `@require`?
- Shall we include the PlotlyBase definitions with `@require`?

I addressed the last point already with another [PR to PlotlyBase](https://github.com/sglyon/PlotlyBase.jl/pull/95). Let's hope that it will be accepted and a new version released.

**Comment by hhaensel** [comment]
One more point:
We may want to move the API from StippleUI to Stipple so that we can use the args/kwargs syntax for all vue elements. That could come in handy when defining plotly...

**Comment by hhaensel** [comment]
Not sure, whether we even may want to define
```julia
StructTypes.omitempties(::Type{StipplePlotly.PlotConfig}) = fieldnames(StipplePlotly.PlotConfig)
```
in order to suppress empty fields from being sent.

**Comment by hhaensel** [comment]
I want to add another very comortable solution, which should work out of the box:
```julia
@reactive! mutable struct Example <: ReactiveModel
    plot::R{Plot} = Plot()
end

function ui(model::Example)
    page(model, class = "container", [
        xelem(:plotly, data = R"plot.data", layout = R"plot.layout", config = R"plot.config")
    ])
end

for i in 1:10
    model.plot[] = Plot(rand(100,2))
    sleep(0.1)
end
```

**Comment by hhaensel** [comment]
Even better:
```julia
plot("plot.data", layout = "plot.layout", config = "plot.config")
```

**Comment by hhaensel** [comment]
Let me put a fully working example here, which we should probably include in StippleDemos...
```julia
using Stipple, StipplePlotly
using PlotlyBase

@reactive! mutable struct Example <: ReactiveModel
    plot::R{Plot} = Plot()
end

function ui(model::Example)
    page(model, class = "container", [
        plot("plot.data", layout = "plot.layout", config = "plot.config")
    ])
end

model = init(Example, debounce=0)
route("/") do
    model |> ui |> html
end

up(8800)

for i in 1:30
    model.plot[] = Plot(rand(100,2))
    sleep(0.1)
end
```

**Comment by hhaensel** [comment]
I couldn't withstand to supply a PR #32 of the version that I would personally favour 😉
It also fixes the problem that we had with the default kwargs of plot.

**Comment by hhaensel** [comment]
I merged the PR and added another fix.
@touchft please close this, if you think that this question is answered. Feel free to test by choosing the master branch
```julia
]add StipplePlotly#master
```

Don't hesitate to comment if you have some more thoughts on this topic.

**Comment by touchft** [comment]
@essenciary @hhaensel Great work!

**Comment by essenciary** [comment]
It's entirely the work of @hhaensel 🚀😍
