### ISSUE TITLE
Cannot Add X and Y Labels to Graph

### ISSUE THREAD

**Issue by TheCedarPrince** [GenieFramework/StipplePlotly.jl#35]
Hi all,

I am attempting to add `xaxis` and `yaxis` labels to my plot but when I specify both axes, only one axis is drawn on the xaxis.
For example, on this figure one can see only the `xaxis` defined:

![image](https://user-images.githubusercontent.com/29561456/165560235-dff7bfb1-ad92-4f71-a137-df1286fa6100.png)

Yet, here is the code:

```julia
    layout::R{PlotLayout} = PlotLayout(
        plot_bgcolor = "#333",
        title = PlotLayoutTitle(text = "Weight Lifted Over Year", font = Font(24)),
	xaxis = [PlotLayoutAxis(title_text = "Date")],
	yaxis = [PlotLayoutAxis(title_text = "Total Weight Lifted per Exercise")],
    )
    config::R{PlotConfig} = PlotConfig()
```

What am I doing wrong here?
This almost seems like a bug but I am unsure.

Thanks!

~ tcp :deciduous_tree:

**Comment by hhaensel** [comment]
For y-axis labelling you need
```julia
PlotLayoutAxis(xy = "y", title_text = "Total Weight Lifted per Exercise")]
```
`xy = "x"` is default, but for better readibility I'd write
```julia
    layout::R{PlotLayout} = PlotLayout(
        plot_bgcolor = "#333",
        title = PlotLayoutTitle(text = "Weight Lifted Over Year", font = Font(24)),
	xaxis = [PlotLayoutAxis(xy = "x", title_text = "Date")],
	yaxis = [PlotLayoutAxis(xy = "y", title_text = "Total Weight Lifted per Exercise")],
    )
    config::R{PlotConfig} = PlotConfig()
```

**Comment by TheCedarPrince** [comment]
That fixed it!
Thanks @hhaensel :smile:
