### ISSUE TITLE
PlotGeoLayout and marker not working maps implementation

### ISSUE THREAD

**Issue by AbhimanyuAryan** [GenieFramework/StipplePlotly.jl#36]
working branch WIP_NewPlots: https://github.com/GenieFramework/StipplePlotly.jl/commit/cd9a835b2925c236e73961e5065e71e5d36de6a5

Implemented Plotly's Geo Layout: https://plotly.com/javascript/reference/layout/geo/

Testing app: 

```julia
using Stipple, StipplePlotly


@reactive! mutable struct Model <: ReactiveModel
    data::R{PlotData} = PlotData(
                            locations= ["FRA", "DEU", "RUS", "ESP"],
                            plot = StipplePlotly.Charts.PLOT_TYPE_SCATTERGEO,
                            mode = "markers",
                            marker = PlotDataMarker(
                                size = [200, 300, 150, 100],
                                color = [10.0, 20.0, 40.0, 50.0],
                                cmin = 0.0,
                                cmax = 50.0,
                                colorscale = "Greens",
                                colorbar = ColorBar(title_text = "Some rate", ticksuffix = "%", showticksuffix = "last"),
                                line = PlotlyLine(color = "black")
                            ),
                            name = "Europe Data")


    layout::R{PlotLayout} = PlotLayout(
        plot_bgcolor = "#333",
        title = PlotLayoutTitle(text="Europe Plot", font=Font(24)),
        geo = PlotLayoutGeo(scope = "asia", resolution="50")
    )
    config::R{PlotConfig} = PlotConfig()
end

function ui(model)
    page(model, class = "container", [
        plot(:data, layout= :layout, config = :config)
    ])
end

route("/") do
    model = Model |> init |> ui |> html
end

up()
```

but it doesn't get added to layout property in `model.js`

```js
  function initStipple(rootSelector){
    Stipple.init({theme: 'stipple-blue'});
    window.Model = new Vue({"el":rootSelector,"mixins":[watcherMixin, reviveMixin],"data":{"isready":false,"config":{"displaylogo":false},"data":[{"mode":"markers","type":"scattergeo","name":"Europe Data","marker":{"color":[10.0,20.0,40.0,50.0],"line":{"color":"black"},"colorbar":{"showticksuffix":"last","title":{"text":"Some rate"},"ticksuffix":"%"},"cmin":0.0,"size":[200,300,150,100],"colorscale":"Greens","cmax":50.0}}],"isprocessing":false,"layout":{"title":{"font":{"family":"'Open Sans', verdana, arial, sans-serif","size":24,"color":"#444"},"text":"Europe Plot"},"plot_bgcolor":"#333"}}});
  }
```

Map should only show `asia` but shows entire world 

<img width="615" alt="Screenshot 2022-05-09 at 12 40 02 PM" src="https://user-images.githubusercontent.com/8083613/167358572-b65c24be-2ee6-4d93-a7ea-bc09f6f07a89.png">

This feature is blocking implementation of any kind of maps: 

Maps scatter https://plotly.com/javascript/scatter-plots-on-maps/
Choropleth Maps https://plotly.com/javascript/choropleth-maps/
Bubble maps https://plotly.com/javascript/bubble-maps/

Another problem with maps is `marker` not working 

```julia
marker = PlotDataMarker(
                size = [200, 300, 150, 100],
                color = [10.0, 20.0, 40.0, 50.0],
                cmin = 0.0,
                cmax = 50.0,
                colorscale = "Greens",
                colorbar = ColorBar(title_text = "Some rate", ticksuffix = "%", showticksuffix = "last"),
                line = PlotlyLine(color = "black")
)
```

but when you see `model.js` marker property seems to be added unlike `geo` 

"marker":{"color":[10.0,20.0,40.0,50.0],"line":{"color":"black"},"colorbar":{"showticksuffix":"last","title":{"text":"Some rate"},"ticksuffix":"%"},"cmin":0.0,"size":[200,300,150,100],"colorscale":"Greens","cmax":50.0}

**Comment by hhaensel** [comment]
Fixed!
:geo was missing in optionals definition in `Dict(::PlotLayout)`

**Comment by hhaensel** [comment]
@AbhimanyuAryan 
If again something new is not appearing in the GUI, the first thing you can check is the `render()` function, in this case
```julia
model = init(Model)
render(model.layout)
```
In this case I found that render calls `Dict()` with a specialised method for `PlotLayout`.

Happy coding 😃

**Comment by AbhimanyuAryan** [comment]
Let me check

**Comment by AbhimanyuAryan** [comment]
Yes it worked :D 

<img width="461" alt="Screenshot 2022-05-10 at 3 07 34 PM" src="https://user-images.githubusercontent.com/8083613/167598828-841c12f6-c0da-402d-b313-fe96d949efcc.png">



```
using Genie
using Genie.Requests, Genie.Renderer
using Stipple, StipplePlotly


Genie.config.cors_headers["Access-Control-Allow-Origin"]  =  "*"
Genie.config.cors_headers["Access-Control-Allow-Headers"] = "Content-Type"
Genie.config.cors_headers["Access-Control-Allow-Methods"] = "GET,POST,PUT,DELETE,OPTIONS"
Genie.config.cors_allowed_origins = ["*"]


@reactive! mutable struct Model <: ReactiveModel
    data::R{PlotData} = PlotData(
                            locations= ["FRA", "DEU", "RUS", "ESP"],
                            plot = StipplePlotly.Charts.PLOT_TYPE_SCATTERGEO,
                            mode = "markers",
                            marker = PlotDataMarker(
                                size = [200, 300, 150, 100],
                                color = [10.0, 20.0, 40.0, 50.0],
                                cmin = 0.0,
                                cmax = 50.0,
                                colorscale = "Greens",
                                colorbar = ColorBar(title_text = "Some rate", ticksuffix = "%", showticksuffix = "last"),
                                line = PlotlyLine(color = "black")
                            ),
                            name = "Europe Data")


    layout::R{PlotLayout} = PlotLayout(
        plot_bgcolor = "#333",
        title = PlotLayoutTitle(text="Asia Plot", font=Font(24)),
        geo = PlotLayoutGeo(scope = "asia", resolution="50")
    )
    config::R{PlotConfig} = PlotConfig()
end

function ui(model)
    page(model, class = "container", [
        plot(:data, layout= :layout, config = :config)
    ])
end

route("/") do
    model = Model |> init |> ui |> html
end

up()
```

**Comment by AbhimanyuAryan** [comment]
because in this case marker was being applied correctly in `model.js` as shown with `init(Model)`

```
Model(Reactive{PlotData}(Observable{PlotData} with 1 listeners. Value:
scattergeo:
plot = scattergeo
locations = ["FRA", "DEU", "RUS", "ESP"]
marker = Layout Legend:
size = [20, 30, 15, 10]
line = Layout Legend:
color = black

color = [10, 20, 40, 50]
cmin = 0.0
cmax = 50.0
colorscale = Greens
colorbar = ColorBar:
ticksuffix = %
showticksuffix = last
title_text = Some rate


mode = markers
name = Europe Data
, 1, false, false), Reactive{PlotLayout}(Observable{PlotLayout} with 1 listeners. Value:
layout:
geo = Layout Geo:
resolution = 50
scope = europe

title = Layout Title:
text = Asia Plot
font = Font("'Open Sans', verdana, arial, sans-serif", 24, "#444")

plot_bgcolor = #333
, 1, false, false), Reactive{PlotConfig}(Observable{PlotConfig} with 1 listeners. Value:
configuration:
displaylogo = false
, 1, false, false), "MWRIWGAMGGFKCPLMHNRUGOXXEXROAZKA", Reactive{Bool}(Observable{Bool} with 1 listeners. Value:
false, 1, false, false), Reactive{Bool}(Observable{Bool} with 1 listeners. Value:
false, 1, false, false))

julia> ^C
```

**Comment by AbhimanyuAryan** [comment]
```
julia> model.data.marker
Layout Legend:
size = [20, 30, 15, 10]
line = Layout Legend:
color = black

color = [10, 20, 40, 50]
cmin = 0.0
cmax = 50.0
colorscale = Greens
colorbar = ColorBar:
ticksuffix = %
showticksuffix = last
title_text = Some rate
```

**Comment by AbhimanyuAryan** [comment]
ok I figured out why marker wasn't rendering. Will push fixes. Output by StipplePlotly 

<img width="407" alt="map" src="https://user-images.githubusercontent.com/8083613/168048601-255630bc-b457-46e1-84c2-7649c71832bd.png">

**Comment by AbhimanyuAryan** [comment]
----closed---- finally

**Comment by cwiese** [comment]
What is the solution cause ?  A bad keyword arg?

See the Layout Legend

│     scatter:
│    plot = scatter
│    labels = ["Sloping Departures", "Violations"]
│    marker = Layout Legend:
│    line = Layout Legend:
│    color = red
│ 
│    symbol = line-ew
│ 
│    mode = markers
│    name = Violation
│    x = ["LAX", "DEN", "IAH", "SFO", "ORD", "IAD"]
│    y = [137, 54, 129, 264, 165, 27]

Produced by this code
"""
    plot_vio = PlotData(x = z[!, grp_col], y = z.Violations, plot = StipplePlotly.Charts.PLOT_TYPE_SCATTER, 
        name = "Violation", labels = [get(column_name_map, grp_col, string(grp_col)), "Violations"],
        mode = "markers", marker = PlotDataMarker(symbol="line-ew", line=PlotlyLine(color="red")),
        )"""

**Comment by AbhimanyuAryan** [comment]
@cwiese don't remember exactly "What is the solution cause? " 
I fixed it a long time back. What are you trying to achieve?

**Comment by cwiese** [comment]
I have found using StipplePlotly frustrating due the fact you're not using Dictionaries for arguments. There many missing attributes for example "shapes" is missing from Layout

**Comment by hhaensel** [comment]
In that case, please use the PlotlyBase interface that we are also supporting.
You find examples in StippleDemos in a dedicated folder

**Comment by hhaensel** [comment]
Event forwarding is independent from the API

**Comment by AbhimanyuAryan** [comment]
@cwiese here are some PlotlyBase examples for StipplePlotly

https://github.com/GenieFramework/StippleDemos/blob/master/StipplePlotly/PlotlyBaseEvents.jl
https://github.com/GenieFramework/StippleDemos/blob/master/StipplePlotly/PlotlyBaseDemo.jl
https://github.com/GenieFramework/StippleDemos/blob/master/StipplePlotly/PlotlyBaseBar.jl


GenieBuilder Demo using PlotlyBase API for StipplePlolty: https://github.com/GenieFramework/ScoringEngineApp 
   - https://github.com/GenieFramework/ScoringEngineApp/blob/master/models/scoringengine/plots.jl
   - https://github.com/GenieFramework/ScoringEngineApp/blob/master/models/scoringengine/explain.jl

**Comment by cwiese** [comment]
THANK YOU!
