### ISSUE TITLE
Link axis in a group plot

### ISSUE THREAD

**Issue by kandolfp** [GenieFramework/StipplePlotly.jl#51]
Thanks to the [example](https://github.com/GenieFramework/StippleDemos/blob/master/StipplePlotly/subplots2x2.jl) I could integrate subplots but I can not manage to link axis together. Is there a possibility?  

What I mean by link: Zoom in one plot and the other plot reacts to the same zoom. In my case only the x-axis.

**Comment by kandolfp** [comment]
Solved: 
For the PlotLayout use: 
`grid = PlotLayoutGrid(rows=2, columns=2, pattern="coupled"),`

and share the `xaxis` between where needed by specifying `xaxis = "x1"' or similar

**Comment by AbhimanyuAryan** [comment]
👍🏻
