### ISSUE TITLE
makie.jl integration for stipple 

### ISSUE THREAD

**Issue by j209** [GenieFramework/StipplePlotly.jl#55]
Hi
Why didn't the Genie team try to integrate [Makie](https://github.com/MakieOrg) to stipple instead of plotly?
Makie is a julia project.

**Comment by AbhimanyuAryan** [comment]
`Makie WebGL` is most suitable for powerful 3D visualization. `Plotly` is defacto/standard for 2D plots and visualizations used across organizations(nvidia, tesla, you name it). We were earlier supporting [ApexCharts ](https://github.com/GenieFramework/StippleCharts.jl) and community was asking for Plotly support so moved to Plotly 

Also makie stack is quite complicated without the help of Makie devs we can't integrate it(or it will take tons of our development time and effort). We have already asked for Makie support here: https://github.com/MakieOrg/Makie.jl/issues/1813

If you can comment their and ask for support. It would be really helpful 🙏
