### ISSUE TITLE
PlotLayoutAxis.xy should not have a default

### ISSUE THREAD

**Issue by ValentinKaisermayer** [GenieFramework/StipplePlotly.jl#66]
`PlotLayout(yaxis=[PlotLayoutAxis(...)])` has the wrong effect since `xy` is `"x"` per default.  Either `PlotLayout` has to reset all `xy` of the `yaxis` to `"y"` or et least not have a default at all. Defaults should be correct 99% of the time.

**Comment by hhaensel** [comment]
I understand that the fix works and will close this issue. Please reopen, if it's still relevant.
