### ISSUE TITLE
Possible typo in Charts.jl line # 587 CONGIG_DEFAULTS

### ISSUE THREAD

**Issue by GenerallyClueless** [GenieFramework/StipplePlotly.jl#67]
**CONGIG**_DEFAULTS ... maybe this should be CONFIG_DEFAULTS

**Comment by GenerallyClueless** [comment]
I see later in lines 845, 846 that CONGIG_DEFAULTS is properly referenced, and assigned to config_defaults, so most likely I am mistaken.  Confirm and I will happily close this issue.

**Comment by GenerallyClueless** [comment]
Should I go ahead and close this ticket, or keep it open?  I really didn't want to keep it open for something like a typo.

**Comment by essenciary** [comment]
You can close it, thanks. I've already fixed it but haven't pushed it yet.
